name: bangtal_memory
description: "방탈출 기록을 하는 어플."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  intl: ^0.18.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  html: ^0.15.4
  custom_rating_bar: ^3.0.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Tenada
      fonts:
        - asset: assets/fonts/Tenada.ttf
